
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend 
    spec:
      containers:
      - name: frontend
        image: 834725375088.dkr.ecr.us-east-1.amazonaws.com/frontend:3.0.8
        ports:
        - containerPort: 80

--- 
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80
    targetPort: 80

--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: frontend.robot51.tk             # Use host only when you need external to internal translation.
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
    